// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeH4pft9iD83webyFevGgh1WfgPcDOcJ4',
    appId: '1:850725976291:web:246a64aa6279457f416dd6',
    messagingSenderId: '850725976291',
    projectId: 'canteen-automation-50311',
    authDomain: 'canteen-automation-50311.firebaseapp.com',
    storageBucket: 'canteen-automation-50311.appspot.com',
    measurementId: 'G-13M4N8Q2LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptgAqM0eB2w2bjB0XweO1nego8IAY5cY',
    appId: '1:850725976291:android:460e0a6a7dec5eeb416dd6',
    messagingSenderId: '850725976291',
    projectId: 'canteen-automation-50311',
    storageBucket: 'canteen-automation-50311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_O-DA8NR7EM9iVlc-8WKSpHJeZ6dUEU',
    appId: '1:850725976291:ios:e3161c0668783f17416dd6',
    messagingSenderId: '850725976291',
    projectId: 'canteen-automation-50311',
    storageBucket: 'canteen-automation-50311.appspot.com',
    iosBundleId: 'com.example.canteenautomation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeH4pft9iD83webyFevGgh1WfgPcDOcJ4',
    appId: '1:850725976291:web:0d5a4e2924fa8347416dd6',
    messagingSenderId: '850725976291',
    projectId: 'canteen-automation-50311',
    authDomain: 'canteen-automation-50311.firebaseapp.com',
    storageBucket: 'canteen-automation-50311.appspot.com',
    measurementId: 'G-0020VYS8B0',
  );
}
